[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }
minijinja = { version = "2.11.0", features = ["json"] }
serde_json = "1.0"
darling = "0.21.3"
proc-macro2 = "1.0.101"
