[package]
name = "crown-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]


[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.3", features = ["derive"] }

[dependencies.crown]
path = "../crown"
features = ["std", "alloc", "password"]

[[bin]]
name = "envelope_fuzz"
path = "fuzz_targets/envelope_fuzz.rs"
test = false
doc = false
bench = false
