[package]
name = "crown-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]


[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.3", features = ["derive"] }
paste = "1.0"

[dependencies.crown]
path = "../crown"
features = ["std", "alloc", "password"]

[[bin]]
name = "envelope_fuzz"
path = "fuzz_targets/envelope_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mac_misc_fuzz"
path = "fuzz_targets/mac_misc_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "kdf_drbg_fuzz"
path = "fuzz_targets/kdf_drbg_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bn_fuzz"
path = "fuzz_targets/bn_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ec_fuzz"
path = "fuzz_targets/ec_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "pq_fuzz"
path = "fuzz_targets/pq_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "rsa_dsa_dh_fuzz"
path = "fuzz_targets/rsa_dsa_dh_fuzz.rs"
test = false
doc = false
bench = false
