//! ChaCha20 assembly implementation.

#[cfg(all(feature = "asm", target_arch = "x86_64"))]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/x86_64.ts"),
    options(att_syntax)
);

extern "C" {
    /// Assembly function for ChaCha20 stream xor on x86_64
    ///
    /// # Parameters
    /// - `out`: Pointer to the output buffer (may equal `inp`)
    /// - `inp`: Pointer to the input buffer
    /// - `len`: Number of bytes to process
    /// - `key`: Pointer to 8 little-endian u32 key words
    /// - `counter`: Pointer to the counter block: counter then 3 nonce words
    fn ChaCha20_ctr32(out: *mut u8, inp: *const u8, len: usize, key: *const u8, counter: *const u8);
}

/// XOR the key stream generated by ChaCha20_ctr32 into `inout` and advance
/// the block counter, mirroring xor_key_stream_blocks_generic.
pub fn xor_key_stream_blocks(d: &mut super::super::Chacha20, inout: &mut [u8]) {
    let mut ctr_block = [0u32; 4];
    ctr_block[0] = d.counter;
    ctr_block[1] = d.nonce[0];
    ctr_block[2] = d.nonce[1];
    ctr_block[3] = d.nonce[2];

    unsafe {
        ChaCha20_ctr32(
            inout.as_mut_ptr(),
            inout.as_ptr(),
            inout.len(),
            d.key.as_ptr() as *const u8,
            ctr_block.as_ptr() as *const u8,
        );
    }

    d.counter += (inout.len() / 64) as u32;
}
