//! ChaCha20 assembly implementation (chacha-x86_64.pl / chacha-armv8.pl).

#[cfg(all(feature = "asm", target_arch = "x86_64"))]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/x86_64.ts"),
    options(att_syntax)
);

// The NEON body calls the SVE entry point when the CPU has SVE, so the SVE
// module of chacha-armv8-sve.pl must be linked alongside it.
#[cfg(crown_aarch64_asm)]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/aarch64.ts"),
    // The aarch64 operands carry `{v0.16b}`-style lane braces.
    options(raw)
);

#[cfg(crown_aarch64_asm)]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/aarch64_sve.ts"),
    // SVE addressing modes carry `{z0.s}`-style lane braces.
    options(raw)
);

extern "C" {
    /// Assembly function for ChaCha20 stream xor
    ///
    /// # Parameters
    /// - `out`: Pointer to the output buffer (may equal `inp`)
    /// - `inp`: Pointer to the input buffer
    /// - `len`: Number of bytes to process
    /// - `key`: Pointer to 8 little-endian u32 key words
    /// - `counter`: Pointer to the counter block: counter then 3 nonce words
    fn ChaCha20_ctr32(out: *mut u8, inp: *const u8, len: usize, key: *const u8, counter: *const u8);
}

/// XOR the key stream generated by ChaCha20_ctr32 into `inout` and advance
/// the block counter, mirroring xor_key_stream_blocks_generic.
///
/// The aarch64 body dispatches on `OPENSSL_armcap_P` itself (SVE, then NEON,
/// then scalar), so the capability word is published first.
pub fn xor_key_stream_blocks(d: &mut super::super::Chacha20, inout: &mut [u8]) {
    let mut ctr_block = [0u32; 4];
    ctr_block[0] = d.counter;
    ctr_block[1] = d.nonce[0];
    ctr_block[2] = d.nonce[1];
    ctr_block[3] = d.nonce[2];

    #[cfg(crown_aarch64_asm)]
    crate::utils::cpuid::armcap();

    unsafe {
        ChaCha20_ctr32(
            inout.as_mut_ptr(),
            inout.as_ptr(),
            inout.len(),
            d.key.as_ptr() as *const u8,
            ctr_block.as_ptr() as *const u8,
        );
    }

    d.counter += (inout.len() / 64) as u32;
}
