//! ChaCha20 assembly implementation (chacha-x86_64.pl / chacha-armv8.pl /
//! chacha-riscv64-v-zbb.pl).

#[cfg(all(feature = "asm", target_arch = "x86_64"))]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/x86_64.ts"),
    options(att_syntax)
);

// The NEON body calls the SVE entry point when the CPU has SVE, so the SVE
// module of chacha-armv8-sve.pl must be linked alongside it.
#[cfg(crown_aarch64_asm)]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/aarch64.ts"),
    // The aarch64 operands carry `{v0.16b}`-style lane braces.
    options(raw)
);

#[cfg(crown_aarch64_asm)]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/aarch64_sve.ts"),
    // SVE addressing modes carry `{z0.s}`-style lane braces.
    options(raw)
);

#[cfg(crown_riscv64_asm)]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/riscv64.ts"),
    options(raw)
);

#[cfg(crown_riscv64_asm)]
core::arch::global_asm!(
    crown_derive::jsasm_file!("crown/src/stream/chacha20/riscv64_zvkb.ts"),
    options(raw)
);

extern "C" {
    /// Assembly function for ChaCha20 stream xor
    ///
    /// # Parameters
    /// - `out`: Pointer to the output buffer (may equal `inp`)
    /// - `inp`: Pointer to the input buffer
    /// - `len`: Number of bytes to process
    /// - `key`: Pointer to 8 little-endian u32 key words
    /// - `counter`: Pointer to the counter block: counter then 3 nonce words
    #[cfg(any(all(feature = "asm", target_arch = "x86_64"), crown_aarch64_asm))]
    fn ChaCha20_ctr32(out: *mut u8, inp: *const u8, len: usize, key: *const u8, counter: *const u8);

    /// The `RV64 V + Zbb` vector body of chacha-riscv64-v-zbb.pl.
    #[cfg(crown_riscv64_asm)]
    fn ChaCha20_ctr32_v_zbb(
        out: *mut u8,
        inp: *const u8,
        len: usize,
        key: *const u8,
        counter: *const u8,
    );

    /// The `Zvkb` build of the same body (`perl chacha-riscv64-v-zbb.pl zvkb`),
    /// which `chacha_riscv.c` prefers when the extension is present.
    #[cfg(crown_riscv64_asm)]
    fn ChaCha20_ctr32_v_zbb_zvkb(
        out: *mut u8,
        inp: *const u8,
        len: usize,
        key: *const u8,
        counter: *const u8,
    );
}

/// `chacha_riscv.c`: the vector body is only taken for a message longer than
/// one block on an 8-byte-aligned buffer. The stream is in-place here, so the
/// input and output alignment tests collapse into one.
#[cfg(crown_riscv64_asm)]
pub fn supported(inout: &[u8]) -> bool {
    use crate::utils::cpuid::{riscv_vlen, riscvcap, RISCV_ZBB};
    inout.len() > 64
        && riscvcap() & RISCV_ZBB != 0
        && riscv_vlen() >= 128
        && inout.as_ptr().align_offset(8) == 0
}

/// XOR the key stream generated by ChaCha20_ctr32 into `inout` and advance
/// the block counter, mirroring xor_key_stream_blocks_generic.
///
/// The aarch64 body dispatches on `OPENSSL_armcap_P` itself (SVE, then NEON,
/// then scalar), so the capability word is published first.
pub fn xor_key_stream_blocks(d: &mut super::super::Chacha20, inout: &mut [u8]) {
    let mut ctr_block = [0u32; 4];
    ctr_block[0] = d.counter;
    ctr_block[1] = d.nonce[0];
    ctr_block[2] = d.nonce[1];
    ctr_block[3] = d.nonce[2];

    #[cfg(crown_aarch64_asm)]
    crate::utils::cpuid::armcap();

    unsafe {
        #[cfg(any(all(feature = "asm", target_arch = "x86_64"), crown_aarch64_asm))]
        ChaCha20_ctr32(
            inout.as_mut_ptr(),
            inout.as_ptr(),
            inout.len(),
            d.key.as_ptr() as *const u8,
            ctr_block.as_ptr() as *const u8,
        );
        #[cfg(crown_riscv64_asm)]
        if crate::utils::cpuid::has_zvkb() {
            ChaCha20_ctr32_v_zbb_zvkb(
                inout.as_mut_ptr(),
                inout.as_ptr(),
                inout.len(),
                d.key.as_ptr() as *const u8,
                ctr_block.as_ptr() as *const u8,
            );
        } else {
            ChaCha20_ctr32_v_zbb(
                inout.as_mut_ptr(),
                inout.as_ptr(),
                inout.len(),
                d.key.as_ptr() as *const u8,
                ctr_block.as_ptr() as *const u8,
            );
        }
    }

    d.counter += (inout.len() / 64) as u32;
}

#[cfg(test)]
mod tests {
    use super::super::super::Chacha20;
    use super::*;

    /// The assembly body must produce the same keystream as the portable
    /// implementation, and advance the counter the same way, for every whole
    /// block count it can be entered with.
    #[test]
    fn asm_matches_generic() {
        for len in [64usize, 128, 192, 256, 320, 576, 1024] {
            let mut key = [0u8; 32];
            rand::fill(&mut key);
            let mut nonce = [0u8; 12];
            rand::fill(&mut nonce);

            let mut buf = alloc::vec![0u8; len];
            rand::fill(&mut buf[..]);

            let mut asm = Chacha20::new(&key, &nonce).unwrap();
            let mut generic = Chacha20::new(&key, &nonce).unwrap();
            let (mut a, mut g) = (buf.clone(), buf.clone());
            asm.xor_key_stream_blocks(&mut a);
            generic.xor_key_stream_blocks_generic(&mut g);

            assert_eq!(a, g, "keystream len={len}");
            assert_eq!(asm.counter, generic.counter, "counter len={len}");
        }
    }

    /// Both riscv64 builds of chacha-riscv64-v-zbb.pl are linked and the
    /// dispatcher picks between them on `RISCV_HAS_ZVKB()`; each body must
    /// reproduce the portable keystream on its own, so that the variant the
    /// current CPU does not select is still covered.
    #[cfg(crown_riscv64_asm)]
    #[test]
    fn riscv64_bodies_match_generic() {
        use crate::utils::cpuid::{has_zvkb, riscv_vlen, riscvcap, RISCV_ZBB};

        if riscvcap() & RISCV_ZBB == 0 || riscv_vlen() < 128 {
            return;
        }
        let bodies: [unsafe extern "C" fn(*mut u8, *const u8, usize, *const u8, *const u8); 2] =
            [ChaCha20_ctr32_v_zbb, ChaCha20_ctr32_v_zbb_zvkb];
        let n = if has_zvkb() { bodies.len() } else { 1 };

        for len in [128usize, 192, 320, 576, 1024] {
            let mut key = [0u8; 32];
            rand::fill(&mut key);
            let mut nonce = [0u8; 12];
            rand::fill(&mut nonce);
            let mut buf = alloc::vec![0u8; len];
            rand::fill(&mut buf[..]);

            let mut generic = Chacha20::new(&key, &nonce).unwrap();
            // The counter block has to be snapshotted before the portable body
            // runs: that call advances `generic.counter`.
            let mut ctr_block = [
                generic.counter,
                generic.nonce[0],
                generic.nonce[1],
                generic.nonce[2],
            ];
            let mut expect = buf.clone();
            generic.xor_key_stream_blocks_generic(&mut expect);

            for (i, body) in bodies[..n].iter().enumerate() {
                let mut out = buf.clone();
                unsafe {
                    body(
                        out.as_mut_ptr(),
                        out.as_ptr(),
                        out.len(),
                        generic.key.as_ptr() as *const u8,
                        ctr_block.as_ptr() as *const u8,
                    );
                }
                assert_eq!(out, expect, "body {i} len={len}");
            }
        }
    }
}
