//! Dump the assembly generated by a jsasm TypeScript generator to stdout.
//!
//! Usage: cargo run -p crown-jsasm --example dump -- crown/src/path/x86_64.ts

fn main() -> anyhow::Result<()> {
    let path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "crown/src/hash/md5/block/x86_64.ts".to_string());

    std::env::set_var(
        "JSASM_VAR",
        r#"{"feature":"","unix":true,"windows":false,"target_family":"unix","target_os":"linux","target_arch":"x86_64","target_vendor":"unknown","target_env":"gnu","target_abi":"","target_pointer_width":64,"target_endian":"little","target_feature":""}"#,
    );

    let out = crown_jsasm::execute_js_with_json_context(path)?;
    print!("{out}");
    Ok(())
}
