name: check-code-style
on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup env
        run: |
          sudo apt update -y
          sudo apt install build-essential gcc cpp libclang-dev openssl libssl-dev -y
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: precommit cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: install Rust 1.85.0
        uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt,clippy
      - name: install taplo
        uses: baptiste0928/cargo-install@v3
        with:
          crate: taplo-cli
      - name: install pre-commit
        run: |
          pip3 install pre-commit
      - name: check style
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: |
          pre-commit run -a
          rustup component remove clippy
          rustup component add clippy
          cargo clippy -- -Dwarnings
          cargo clippy --tests -- -Dwarnings
          cargo clippy --no-default-features -- -Dwarnings
          cargo clippy --no-default-features -F alloc -- -Dwarnings
          cargo clippy --no-default-features -F std -- -Dwarnings
