name: check-fuzz-testing
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fuzzing:
    name: Run Fuzzing (3 Hours)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        uses: taiki-e/install-action@v2.87.1
        with:
          tool: cargo-fuzz

      - name: Run envelope_fuzz (3 hours)
        run: |
          cargo +nightly fuzz run envelope_fuzz --target=x86_64-unknown-linux-gnu -- -max_total_time=10800

      - name: Upload crashes if any
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-crashes
          path: fuzz/artifacts/
