name: publish-npm

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-wasm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: setup env
        run: |
          sudo apt update -y
          sudo apt install build-essential gcc cpp libclang-dev openssl libssl-dev -y

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.92.0

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Copy README and LICENSE
        run: |
          cp README.md crown-wasm/
          cp LICENSE crown-wasm/

      - name: Build wasm package
        working-directory: crown-wasm
        run: wasm-pack build --scope cathaysia --target bundler

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Publish to npm
        working-directory: crown-wasm/pkg
        run: npm publish --registry=https://registry.npmjs.org/

      - name: Publish to jsr
        working-directory: crown-wasm
        run: npx jsr publish --allow-dirty
